### ISSUE TITLE
not showing team drive 

### ISSUE THREAD

**Issue by begginer-123** [ParveenBhadooOfficial/Bhadoo-Drive-Index#16]
i have added shared drive folder but it still shows my own whole drive. not the shared drive

<a href="https://ibb.co/1JGbVyP"><img src="https://i.ibb.co/4gRJyvX/Screenshot-40.png" alt="Screenshot-40" border="0" /></a>

**Comment by ParveenBhadooOfficial** [comment]
use incognito mode because cache causes that problem. Also the screenshot doesn't shows what you're asking.

**Comment by begginer-123** [comment]
> use incognito mode because cache causes that problem. Also the screenshot doesn't shows what you're asking.

still the same even in incognito and i deployed for the first time. the screenshot was to show you that i have enabled the shared drive.

**Comment by ParveenBhadooOfficial** [comment]
if you changed something in the screenshot you're doing it wrong. don't change anything in code. just enter the shared drive id from drive.google.com site.

**Comment by begginer-123** [comment]
found the issue, even after entering shared drive id in the generator, it was still filling the option as root. so i edited the value. now its all good. I am really a fan of your work. i hope you keep up the good work.
