### ISSUE TITLE
With this we can bypass the Download Limit from Google?

### ISSUE THREAD

**Issue by ZeroCool22** [ParveenBhadooOfficial/Bhadoo-Drive-Index#18]
I see we can put our files on **"Private"** mode on our G. Drive, but ppl will still can download it trough the index.
So we can keep our file as Private and share the index link, it's a Win/Win.

**Comment by ParveenBhadooOfficial** [comment]
With this we can bypass the Download Limit from Google?

No. I had a solution but as Google changed everything now so my method doesn't works. For now.

**Comment by ZeroCool22** [comment]
> 
> 
> With this we can bypass the Download Limit from Google?
> 
> No. I had a solution but as Google changed everything now so my method doesn't works. For now.

Oh, you are talking about the **"Make a Copy"** method? Yes they fucked up this, now that method doesn't works anymore.

**Comment by ParveenBhadooOfficial** [comment]
No, different method. But doesn't works anymore.

**Comment by ZeroCool22** [comment]
> 
> 
> No, different method. But doesn't works anymore.

Ok, thx for your reply.
