### ISSUE TITLE
File Size in Lite mod And Dark Mode

### ISSUE THREAD

**Issue by Dariushg75** [ParveenBhadooOfficial/Bhadoo-Drive-Index#2]
Hi,

Thanks for Share GDIndex with lite mod.

i have some problem.

1. i need file size in lite mod.
2. can use dark mod on lite mod?

like this site : https://msdn.hackerc.at/

thanks

**Comment by ParveenBhadooOfficial** [comment]
Sure, Will implement soon.

**Comment by Dariushg75** [comment]
hi, not fixing for my request? :(

**Comment by ParveenBhadooOfficial** [comment]
While I've redesigned the Index. Dark Mode is coming soon.
