### ISSUE TITLE
Index only Team Drive?

### ISSUE THREAD

**Issue by sagirisayang** [ParveenBhadooOfficial/Bhadoo-Drive-Index#3]
In the code generator, I entered my Team Drive into the default root ID. But when I open the app, it indexes throughout my entire drives instead of only my Team Drive.

Can you give a feature that limits how far someone can explore the index?

**Comment by ParveenBhadooOfficial** [comment]
use [this](https://github.com/ParveenBhadooOfficial/Bhadoo-Drive-Index/blob/master/worker/dist/goindex.js)
