### ISSUE TITLE
Why you wont add preview feature

### ISSUE THREAD

**Issue by cloudoftg** [ParveenBhadooOfficial/Bhadoo-Drive-Index#6]
Will you add preview feature if yes when any ETA? I mean thumbnail on the page. like alx. any how can i search in all the drives from the main page. because i have added many drives

**Comment by ParveenBhadooOfficial** [comment]
Please explain your first query. And searching in all drives is not supported by Google yet. I think. And loop will cause errors. So no ETA on that.
